### ISSUE TITLE
Wasm32 support

### ISSUE THREAD

**Issue by cdmurph32** [Cykooz/fast_image_resize#10]
First I'd like to say this crate definitely fills a need for Rust. Thank you so much.

Is there any intention of adding wasm32 support?

**Comment by Cykooz** [comment]
In the next major release I plan to add multi-threading support.
After that I will try to add support for WASM.

**Comment by cdmurph32** [comment]
That's great. Thanks again.

**Comment by cdmurph32** [comment]
I opened https://github.com/Cykooz/fast_image_resize/pull/11 for this. Threads could get tricky with WASM, so I wanted support in the current version of the repo. Please feel free to ignore it for now.
