### ISSUE TITLE
num-traits error

### ISSUE THREAD

**Issue by Sparkenstein** [Cykooz/fast_image_resize#19]
cool crate 👍 . I was trying it out, but couldn't get it to work. 

![image](https://github.com/Cykooz/fast_image_resize/assets/24642451/3b6fb254-50be-41ec-b183-ad2545156083)

I believe latest version was just released about an hour ago, I tried a prev version as well, kept getting the same error. am I missing some dependency? 

My entire code is just 

```toml
fast_image_resize = "3.0.2"
```
 in Cargo.toml and importing fr nothing else

**Comment by Cykooz** [comment]
@Sparkenstein I think that your build uses very old version of `num_traits` (< 0.2.15). Try to run `cargo update` and build again. 
I tested my crate with `num_traits` == 0.2.17.

**Comment by Cykooz** [comment]
I have released `fast_image_resize v3.0.3` where I fixed a minimal required version of `num-traits`.
