### ISSUE TITLE
f32 example

### ISSUE THREAD

**Issue by manzt** [Cykooz/fast_image_resize#21]
Thanks for making this library! I'd like to try to use it for a `Vec<f32>` source. I'm fairly new to rust and can seem to create the appropriate `ImageView` or `Image` structs. Is there an example of the resizing for `F32`? Thanks in advance!

```rust
impl Matrix<f32> {
    pub(crate) fn to_image_view(&self) -> ?? {
        let (height, width) = self.shape();
        let img = fr::ImageView::new(
            fr::NonZeroU32::new(width as u32).unwrap(),
            fr::NonZeroU32::new(height as u32).unwrap(),
            self.data(), // Vec<f32>
        );
        img
    }
}
```

**Comment by Cykooz** [comment]
`ImageView` is a generic struct that doesn't own the image data. It owns only vector of slices with an image rows.
Method `ImageView::new()` takes `Vec<&[P]>`, where `P` is generic parameter and must be one of pixel types are provided by `fast_image_resize` (U8, U8x2,... U8x4,... U16x4, ... F32).

Also you can create `ImageView` instance from following slice types:
- `&[u8]` with help of method [ImageView::from_buffer()](https://docs.rs/fast_image_resize/3.0.4/fast_image_resize/struct.ImageView.html#method.from_buffer)
 ```rust
 let buffer: &[u8] = ...;
 let img_view: ImageView<F32> = ImageView::from_buffer(width, height, buffer).unwrap();
 ```
- `&[F32]` with help of method [ImageView::from_pixels()](https://docs.rs/fast_image_resize/3.0.4/fast_image_resize/struct.ImageView.html#method.from_pixels)
 ```rust
 let f32_pixels: &[F32] = ...;
 let img_view = ImageView::from_pixels(width, height, f32_pixels).unwrap();
 ```

Result of all of these methods will be `ImageView<F32>`.

----

If you want to get a struct that owns an image data, then you may use `Image` struct as a simple implementation of such type of container.
```rust
let empty_image = Image::new(width, height, PixelType::F32);
...
let image_data: Vec<u8> = ...;
let image = Image::from_vec_u8(width, height, image_data, PixelType::F32).unwrap();
```
