### ISSUE TITLE
no gaussian kernel

### ISSUE THREAD

**Issue by Lishen1** [Cykooz/fast_image_resize#22]
unexpected but here no standard gaussian kernel as opencv has https://docs.opencv.org/4.x/d4/d1f/tutorial_pyramids.html

**Comment by Cykooz** [comment]
The `interpolation` argument of the [resize() function](https://docs.opencv.org/4.x/da/d54/group__imgproc__transform.html#ga47a974309e9102f5f08231edc7e7529d) has no value which mentions a Gaussian kernel:

https://docs.opencv.org/4.x/da/d54/group__imgproc__transform.html#ga5bb5a1fea74ea38e1a5445ca803ff121

**Comment by Lishen1** [comment]
it used here https://docs.opencv.org/4.x/d4/d86/group__imgproc__filter.html#gaf9bba239dfca11654cb7f50f889fc2ff
special case of 2 times downsampling

**Comment by Cykooz** [comment]
You may use [custom filter](https://docs.rs/fast_image_resize/3.0.4/fast_image_resize/enum.FilterType.html#variant.Custom) to implement Gaussian filter.

In other libraries (Pillow, libvips, OpenCV) I didn't see the use of Gaussian kernel for an "universal" resize function.
Usually these libraries use a Gaussian filter to blur images.

**Comment by Lishen1** [comment]
yep, thanks,  custom filter is a way. a little bit confused by using f64 (i think it's too precise ) . btw this lib has gaussian filter
https://github.com/image-rs/image/blob/2b513ae9a6ac306e752914f562e7d408f096ba3f/src/imageops/sample.rs#L909

**Comment by Cykooz** [comment]
Thank you for link to Gaussian implementation from image-rs. I will use it to add Gaussian filter into ``fast_image_resize`` in future.

**Comment by Cykooz** [comment]
> a little bit confused by using f64

I copied it from `Pillow` - https://github.com/python-pillow/Pillow/blob/main/src/libImaging/Resample.c
I don't know why they decided to use `double` instead of `float`.

**Comment by Cykooz** [comment]
I have added Gaussian filter in version 4.0.0
