### ISSUE TITLE
Equivalent to OpenCV cv2.INTER_AREA?

### ISSUE THREAD

**Issue by FSund** [Cykooz/fast_image_resize#23]
Is there an equivalent to OpenCV's INTER_AREA algorithm in `fast_image_resize`?

See comparison here: https://gist.github.com/georgeblck/e3e0274d725c858ba98b1c36c14e2835

**Comment by Cykooz** [comment]
I am not sure, but if consider the information from [the article](https://medium.com/@wenrudong/what-is-opencvs-inter-area-actually-doing-282a626a09b3) it may be implemented with help of custom filter:
```rust
fn area_filter(mut x: f64) -> f64 {
    x = x.abs();
    if x < 0.5 {
        1.0 - 2.0 * x
    } else {
        0.0
    }
}
```

**Comment by Cykooz** [comment]
I am not sure, but if consider the information from [the article](https://medium.com/@wenrudong/what-is-opencvs-inter-area-actually-doing-282a626a09b3) it may be implemented with help of custom filter:
```rust
fn area_filter(mut x: f64) -> f64 {
    x = x.abs();
    if x < 0.5 {
        1.0 - 2.0 * x
    } else {
        0.0
    }
}

let area = FilterType::Custom(
    Filter::new("Area", area_filter, 0.5).unwrap()
);
```

**Comment by FSund** [comment]
Thanks, I'll give that a go!
