### ISSUE TITLE
wrong image color

### ISSUE THREAD

**Issue by Kevin301099** [Cykooz/fast_image_resize#24]
After ![hello](https://github.com/Cykooz/fast_image_resize/assets/49025655/40fe1f0d-1caa-4779-87a6-666399a1765a)
Before(Original image) ![iPhone14Pro_ProRAW48MP](https://github.com/Cykooz/fast_image_resize/assets/49025655/9236d273-f76d-47a2-a45f-eafdd6b0d3c9)

**Comment by Cykooz** [comment]
The original image contains `Display P3` color profile. The result image doesn't contain it.
The `fast_image_resize` knows nothing about color profiles or color spaces. It works with raw pixel values.
If you want to get correct colors, you should at least add the color profile from the source image-file into the result image-file.
Ideally, you should convert the source pixels to a linear color space before resizing, and convert them back after resizing.

**Comment by Kevin301099** [comment]
can you suggest library for do this ?

**Comment by Cykooz** [comment]
Honestly, I don't see any difference in the color of these images on my computer.

**Comment by Cykooz** [comment]
But I see that you use Nearest algorithm to resize the image. 
That is the result of using `Convolution(Filter::Lanczos3)` algorithm:
![4-res](https://github.com/Cykooz/fast_image_resize/assets/163725/6d5d34ed-1929-4020-bcae-949bb2a08a91)

**Comment by Cykooz** [comment]
1. Your result with Nearest algorithm
2. Resize with Convolution algorithm in sRGB color space
3. Resize with Convolution algorithm in linear color space
![res](https://github.com/Cykooz/fast_image_resize/assets/163725/163dbb21-91ba-49f1-8fe2-a10b018acea8)

**Comment by Cykooz** [comment]
I opened the original image in my browser and now I see the color difference. I think my default image viewer doesn't support color profiles. And that's the reason why I didn't see the difference at first.

**Comment by Cykooz** [comment]
> can you suggest library for do this ?

Sorry, I can't suggest any library right now. I haven't had to work with color profiles yet.

**Comment by Kevin301099** [comment]
ok, thank you.

**Comment by Cykooz** [comment]
The first crate I found on google was https://github.com/kornelski/rust-lcms2.
