### ISSUE TITLE
Are the examples updated to the last version?

### ISSUE THREAD

**Issue by qiqetes** [Cykooz/fast_image_resize#27]
```
error[E0599]: no method named `typed_image` found for enum `DynamicImage` in the current scope
  --> src/main.rs:16:51
   |
16 |     let src_view: TypedImageRef<U8x4> = src_image.typed_image().unwrap();
   |                                                   ^^^^^^^^^^^
   |
help: there is a method `type_id` with a similar name
   |
16 |     let src_view: TypedImageRef<U8x4> = src_image.type_id().unwrap();
   |                                                   ~~~~~~~

```
When I use the example code

**Comment by qiqetes** [comment]
No problem with typed_image in the 3.0.4 version

**Comment by qiqetes** [comment]
`
use std::io::BufWriter;

use fast_image_resize::Resizer;
use image::io::Reader as ImageReader;

use fast_image_resize::images::{Image, ImageRef};
use image::codecs::png::PngEncoder;
use image::{ExtendedColorType, ImageEncoder};
`
Those are my imports. Still getting the same error.

Yup, It doesn't have the method `typed_image()`, I confused it with `pyxel_type()`
`fast_image_resize = {version = "4.0.0", features=["image"]}` I'm kind of new to rust, so probably I got something wrong, but everything was workign for me on the 3.0.4 and now can't get it to work

**Comment by qiqetes** [comment]
It appears to be working now. I haven't made any changes to the .toml file. Apologies

**Comment by Shaphil** [comment]
I am now getting a similar error with the example from https://github.com/Cykooz/fast_image_resize?tab=readme-ov-file#resize-rgba8-image.

Getting 
```
Method `pixel_type` not found in the current scope for type `DynamicImage` [E0599]
```
for the following part of the example,

```rust
let mut dst_image = Image::new(
        dst_width,
        dst_height,
        src_image.pixel_type().unwrap(),
    );
```

and, there is in fact no `pixel_type()` in `dynimage.rs`. what am I doing wrong?
