### ISSUE TITLE
Support for `F32x2` `F32x3` & `F32x4`?

### ISSUE THREAD

**Issue by virtualritz** [Cykooz/fast_image_resize#30]
Specifically for `f32` `TIFF`s and `OpenEXR`s.

I can provide such files, to add to the `data` folder.

**Comment by Cykooz** [comment]
It will be good if you attach example files.

**Comment by virtualritz** [comment]
Here is a [bunch of OpenEXRs](https://github.com/user-attachments/files/15855652/j0.3toD__OpenEXRs.zip). The names should explain what the data in there looks like.

Images were generated by me, I hereby put them under a [CC0](https://creativecommons.org/publicdomain/zero/1.0/) license.

**Comment by Cykooz** [comment]
Thank you. But it seems that I can convert existing images on the fly to `F32xN` format for testing purposes.

**Comment by virtualritz** [comment]
Indeed, Krita or GraphicsMagick/ImageMagick or the like will do your bidding here.

The former is how I generated all those from a single `F16x4` source.

P.S.: I can btw. also add `F16x4` samples.
It would be great to support the `F16` types as well, behind a `half` feature that pulls in the resp. crate. :grin:

**Comment by virtualritz** [comment]
Btw, if there are any theoretical speed gains when doing e.g. three times a `F32x3` vs. doing a `F32x9`?
I.e. would it make sense, speed-wise, to support higher numbers than 4 for the channels (or even `const`-generics)?

OpenEXRs often have a lot of extra layers. E.g. normal (`F32x3`), albedo (`F32x3`) etc.

**Comment by Cykooz** [comment]
> It would be great to support the F16 types as well, behind a half feature that pulls in the resp. crate. 😁

I think it will be possible with help of converting a `f16`-image into `f32`-one. As I know, modern CPUs haven't instructions to operate with f16 data type.

**Comment by Cykooz** [comment]
> Btw, if there are any theoretical speed gains when doing e.g. three times a F32x3 vs. doing a F32x9?
> I.e. would it make sense, speed-wise, to support higher numbers than 4 for the channels (or even const-generics)?

If I do it in a generic style I will have to rename the crate to `slow_image_resize` :-)

Every pixel type that I add into the crate requires a lot of unique code and a lot of time to run benchmarks. 
So it is possible to add `F32x9` but I doubt it's worth the effort.

**Comment by virtualritz** [comment]
> I think it will be possible with help of converting a f16-image to f32-one. As I know, modern CPUs haven't instructions to operate with f16 data type.

Rust [will "soon" have native `f16` support](https://github.com/rust-lang/rust/issues/116909) which may make things easier. :grin:.

**Comment by virtualritz** [comment]
Also, there are finally some crates that do not render to stupid, non-linear `u8`. :wink:

E.g. Google's [`forma`](https://crates.io/crates/forma-render) uses an [`[[f16; 4]]`](https://docs.rs/forma-render/0.1.3/src/forma_render/styling.rs.html#273-284) as storage for it's buffers.

**Comment by Cykooz** [comment]
I released version 4.1 with support of `F32x2`, `F32x3` and `F32x4` pixels.
