### ISSUE TITLE
how do you apply a crop on the target buffer?

### ISSUE THREAD

**Issue by TroyKomodo** [Cykooz/fast_image_resize#31]
Previously in older versions we used to be able to provide a crop on both the input and output buffer in the resize function.

if i want to take a subsection of a source image and then impose it upon the dest image at a different sub section.

![how-to](https://github.com/Cykooz/fast_image_resize/assets/49777269/33d25a0e-a201-4a99-90c1-04136134447d)

**Comment by TroyKomodo** [comment]
```rs
view.set_crop_box(crop)?;

let mut target_view = if resize_dims != output_dims {
	target_image.view_mut().crop(left, top, width, height)?
} else {
	target_image.view_mut()
};

resizer.resize(&view, &mut target_view)?;
```

**Comment by Cykooz** [comment]
In the new version you have to use `CroppedImageMut` or `TypedCroppedImageMut` wrapper for destination image.

```rust
use fast_image_resize::images::CroppedImageMut;

let mut cropped_target_image = CroppedImageMut::new(
    &mut target_image, 
    left, 
    top, 
    width,
    height,
).unwrap();

let mut resizer = fr::Resizer::new();
resizer
    .resize(
        &src_image,
        &mut cropped_target_image,
        None,
    )
    .unwrap();
```

**Comment by TroyKomodo** [comment]
I see thank you, is there a difference to applying a crop on the resize options vs submitting a CroppedImage as the source?

**Comment by Cykooz** [comment]
ResizeOptions uses  `f64` type for crop parameters. It allows you to prevent proportions distortion.
And maybe image resizing will be little bit faster with the options than with `CroppedImage`.

**Comment by Cykooz** [comment]
Also, cropping with ResizeOptions can use pixels outside the crop box if needed for the convolution process in areas near the edges of the crop box.
