### ISSUE TITLE
Equivalent to OpenCV `cv2.INTER_LINEAR`

### ISSUE THREAD

**Issue by bedapisl** [Cykooz/fast_image_resize#32]
Hello is it possible to achieve exactly same results with this library as if I was using `cv2.resize` with `interpolation=cv2.INTER_LINEAR` from OpenCV?

I tried using `Resizer::new(Convolution(Bilinear))` but the pixel values in the resulting image are slightly different.

Thanks

**Comment by Cykooz** [comment]
Do you ask about downscaling and upscaling?

**Comment by Cykooz** [comment]
As I understand, OpenCV uses "convolution" with fixed kernel size (it is essentially just Affine Transformations). In this case, downscaling very big image into very small one looks like a result of nearest "interpolation".

`fast_image_resize` uses convolution with adaptive kernel size. It requires more computations but makes more better result.
[Look at results](https://github.com/Cykooz/fast_image_resize/issues/12#issuecomment-1804615516) of downscaling big image into small one with use of different OpenCV interpolations.

**Comment by bedapisl** [comment]
Downscaling is more important but I would ideally I would like both.

Yes, I see the results are visually better. But my goal is to reproduce a pipeline written in Python that uses OpenCV. I need exactly same results as in the OpenCV, no matter which ones look better.

**Comment by Cykooz** [comment]
I can try to implement a fixed kernel size, but I'm not sure if that would be enough to get exactly the same results. The result also depends on how a particular solution handles rounding of numbers, accuracy of intermediate calculations and other things.

**Comment by bedapisl** [comment]
Hello, can I ask you about some rough time estimate for this? Alternatively if you don't have time for it, I can try implementing it myself and send it to you for review.

**Comment by Cykooz** [comment]
I think I can do it for about 5-7 days. But I don't know how call this method of resize.

**Comment by bedapisl** [comment]
I think both name syou suggested make sense, I don't have any other idea.

**Comment by Cykooz** [comment]
I implemented `Interpolation` resize algorithm. I did the simple test to compare the result of `Interpolation(FilterType::Bilinear)` with the result of `INTER_LINEAR` from OpenCV. They look the same.

**Comment by bedapisl** [comment]
Perfect thanks. I will try it later.

**Comment by Cykooz** [comment]
I will publish this version on crates.org within 1-2 days.

**Comment by Cykooz** [comment]
I released version 4.2.0
