### ISSUE TITLE
Inaccurate colors appear in the corners of the image after scaling

### ISSUE THREAD

**Issue by LazyIonEs** [Cykooz/fast_image_resize#33]
我通过`resizer.resize`方法将此**512*512**的图片缩放到**192*192**，缩放算法使用了`Lanczos3`，缩放后的图片四角出现了与原图不一致的颜色，我在使用[resize](https://github.com/PistonDevelopers/resize)时，同样适用了`Lanczos3`，但并没有这个情况，麻烦看一下这个是什么原因

I scaled this **512*512** image to **192*192** using the `resizer.resize` method. The scaling algorithm used `Lanczos3`. The four corners of the scaled image had inconsistent colors with the original image. When I used [resize](https://github.com/PistonDevelopers/resize), I also applied `Lanczos3`, but this problem did not occur. Please take a look at what is the reason

与原图对比 - Compare with original image
![image](https://github.com/Cykooz/fast_image_resize/assets/86482436/80fd5bda-6d8d-4354-81f8-279436742a81)

缩放之前 - Before scaling
![512](https://github.com/Cykooz/fast_image_resize/assets/86482436/5bfbf688-0b5d-4dfb-bf33-b11c4343af57)

缩放之后 - After scaling
![asdasd](https://github.com/Cykooz/fast_image_resize/assets/86482436/5d9767b5-b9b5-4a37-b442-a03464d3922b)

**Comment by Cykooz** [comment]
Could you attach zip-file with the image before scaling?

**Comment by Cykooz** [comment]
What version of fast_image_resize are you using?

**Comment by Cykooz** [comment]
This is a known disadvantage of such filters (bicubic filters, lanczos3). This effect is called "ghosting" or "glow". 
You may use one of bilinear filters if this effect is not appropriate for you.

I don't know why in the "resize" crate this effect is almost invisible for RGBA images. But for images without alpha channel this effect is the same as for fast_image_resize.

**Comment by LazyIonEs** [comment]
我参考了[squoosh](https://github.com/GoogleChromeLabs/squoosh/blob/dev/codecs/resize/src/lib.rs)中`resize`的调用，当我启用了`premultiply`和`color_space_conversion`，所得到的结果非常的好，比较符合我的需求，但是相比于`reszie`，我更想使用`fast_image_resize`，因为这对于我这个新手来说简单很多，是个很不错的开源库，我不知道这对你是否有帮助。我会尝试其他的过滤器，看看能不能达到我想要的效果

I referred to the call of `resize` in [squoosh](https://github.com/GoogleChromeLabs/squoosh/blob/dev/codecs/resize/src/lib.rs). When I enabled `premultiply` and `color_space_conversion`, the results were very good and more in line with my needs. However, compared to `reszie`, I would rather use `fast_image_resize` because it is much simpler for a novice like me and is a very good open source library. I don't know if this is helpful to you. I will try other filters to see if I can achieve the effect I want.

squoosh - resize
![ic_launcher_resize_resize_Lanczos3](https://github.com/Cykooz/fast_image_resize/assets/86482436/92bd9aad-1173-4b9e-81d2-062df1641a78)

fast_image_resize
![ic_launcher_resize_fast_image_resize_Lanczos3](https://github.com/Cykooz/fast_image_resize/assets/86482436/f912ebdc-f093-4acd-b0ab-700b75ef377d)

**Comment by LazyIonEs** [comment]
我尝试使用了`fast_image_resize`中的`Mitchell`和`CatmullRom`，他们也出现了你所说的"ringing"，这个结果对我来说很不好，对于"ringing"，`Mitchell`相比于`CatmullRom`来说要少很多

I tried using `Mitchell` and `CatmullRom` in `fast_image_resize`, and they also had the "ringing" you mentioned. This result is not good for me. `Mitchell` has much less "ringing" than `CatmullRom`.

Mitchell
![ic_launcher_resize_Mitchell](https://github.com/Cykooz/fast_image_resize/assets/86482436/901c6e43-aac2-4fcc-9343-60886ae5ca1a)

CatmullRom
![ic_launcher_resize_CatmullRom](https://github.com/Cykooz/fast_image_resize/assets/86482436/a11ef5a4-0dff-4855-a6ff-09d249faf82a)

**Comment by Cykooz** [comment]
Mitchel and CatmulRom are bicubic filters, they also have this effect.

**Comment by LazyIonEs** [comment]
> Mitchel and CatmulRom are bicubic filters, they also have this effect.

Yes, I misunderstood what you meant. I used `Bilinear` for testing, but the clarity is not as good as `Lanczos3`, which may not meet my needs. Thank you.

**Comment by Cykooz** [comment]
No, this is a known property of such filters.
You may use bilinear filters or make yoursefl custom filter.
There is no the one good filter for all cases. You have to choose filter for particular case.

**Comment by LazyIonEs** [comment]
> No, this is a known property of such filters. You may use bilinear filters or make yoursefl custom filter. There is no the one good filter for all cases. You have to choose filter for particular case.

好的，谢谢
OK, thanks
