### ISSUE TITLE
resize-rgba8-image example uses a no longer supported function.

### ISSUE THREAD

**Issue by SunnyWar** [Cykooz/fast_image_resize#34]
[https://docs.rs/fast_image_resize/latest/fast_image_resize/#resize-rgba8-image](url)
This line:
let mut dst_image = Image::new(
        dst_width,
        dst_height,
        src_image.pixel_type().unwrap(),
    );
    
pixel_type() is not longer supported in the image crate.

**Comment by Cykooz** [comment]
It is not from 'image' crate. 'pixel_type()' is method of [fast_image_resize::IntoImageView](https://docs.rs/fast_image_resize/latest/fast_image_resize/trait.IntoImageView.html) trait.

**Comment by vincent-vinf** [comment]
@SunnyWar The image feature of the fast_image_resize must be enabled for the compilation to succeed, change the dependencies in Cargo.toml
```toml
[dependencies]
fast_image_resize = { version = "5.0.0", features = ["image"] }
```
