### ISSUE TITLE
the lasted resized example cannot be compiled correctly

### ISSUE THREAD

**Issue by drharryhe** [Cykooz/fast_image_resize#35]
the error msg is as followed:
<img width="1043" alt="image" src="https://github.com/user-attachments/assets/cb6395e1-3a30-44a5-91c1-fbfa1aa48a77">

Actually, resize() needs IntoImageView ,but the passed src_image is DynamicImage which does not implement IntoImgeView

**Comment by Cykooz** [comment]
You must enable `"image"` feature to support of `image::DynamicImage`. This is written before the example in README.md.

**Comment by drharryhe** [comment]
my fault. thanks a lot
