### ISSUE TITLE
Doesn't support zoom.

### ISSUE THREAD

**Issue by AurevoirXavier** [Cykooz/fast_image_resize#38]
Is possible to zoom an image just like the `image` crate.

Or it this goal to be fast crop instead of fast resize?

**Comment by Cykooz** [comment]
It is possible to upscale images. Do you have any difficulty with this?

**Comment by AurevoirXavier** [comment]
> It is possible to upscale images. Do you have any difficulty with upscaling?

Sorry is there an example for this?

I follow the existing example to create an image struct as the dest and call resize on it. If the size is smaller than the original it works. If its size is larger than the original then it panic with doesn't fit the size.

**Comment by Cykooz** [comment]
It is strange. Could you give example of your code and sizes of source and destination images?
