### ISSUE TITLE
Not as fast as expected ?

### ISSUE THREAD

**Issue by kpouer** [Cykooz/fast_image_resize#39]
Hey,
I am tring to resize images, they are not so big but the performances are not even close to your benchmarks : here is my example :

```rust 
fn resize_simd() {
    let src = Image::new(320, 200, U8x3);
    let mut dest = Image::new(320 * 3, 200 * 3, U8x3);
    let mut resizer = Resizer::new();
    let options = ResizeOptions::new().resize_alg(ResizeAlg::Nearest);
    unsafe { resizer.set_cpu_extensions(CpuExtensions::Neon); }
    let start = std::time::Instant::now();
    resizer.resize(&src, &mut dest, &options).unwrap();
    println!("Elapsed simd: {}ms", start.elapsed().as_millis());
}
```

I'm on a Mac M1 so I use Neon, but I only get around 10ms to do this.
In fact activating Neon changes almost nothing.
Any idea what is wrong ? Eventually Neon is not optimized for Mac Arm ?

**Comment by Cykooz** [comment]
Nearest algorithm doesn't use any SIMD optimization. It doesn't have a lot of computations. It is just copying pixels with fixed step.

In my benchmarks I reduce size of an image. Your example is about enlarging an image. It is little bit different case.

**Comment by kpouer** [comment]
Oh thanks for the explanations, in fact it's for an emulator so the incoming resolution is fixed but I would like to adapt to big screens. I will try different approach, thanks.
