### ISSUE TITLE
LumaA pixels

### ISSUE THREAD

**Issue by indietyp** [Cykooz/fast_image_resize#6]
Hi, I see that this project is able to resize a lot of different values but U8x2 seems to be missing.

What is the recommended strategy of working with LumaA pixels?

**Comment by Cykooz** [comment]
I'll can try to add support for images with U8x2 pixels.

**Comment by indietyp** [comment]
that would be awesome!

**Comment by Cykooz** [comment]
https://crates.io/crates/fast_image_resize/0.9.0
